<#
.SYNOPSIS
    Silent installation of Document Workbench (Belge Tezgahi) with an optional central IT policy.

.DESCRIPTION
    1. Installs the .msi silently (no dialogs, no restart) and writes an installer log.
    2. Installs the central policy to %ProgramData%\DocumentWorkbench\policy.properties - either a prepared
       file (-Policy) or one generated from the switches below.
    3. Locks the policy folder: Administrators and SYSTEM full control, Users read-only. Well-known SIDs are
       used, so this works on Turkish, English or any other Windows language.

    Run from an elevated PowerShell, or push it with your software deployment tool (Intune, SCCM, GPO
    startup script, PDQ...). Exit code 0 = success.

.EXAMPLE
    .\Install-DocumentWorkbench.ps1 -Installer .\DocumentWorkbench-1.0.0.msi -Policy .\policy.properties

.EXAMPLE
    .\Install-DocumentWorkbench.ps1 -Installer .\DocumentWorkbench-1.0.0.msi -DisableAI -DisableWeb `
        -ReportFolder '\\fileserver\it\dwb-health' -AdminPassphraseHash 'pbkdf2$120000$...'
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)] [string] $Installer,
    [string] $Policy,
    [switch] $DisableAI,
    [switch] $DisableWeb,
    [switch] $DisableLan,
    [switch] $RequireLanSecret,
    [string] $AdminPassphraseHash,
    [string] $ReportFolder,
    [ValidateRange(5, 1440)] [int] $ReportIntervalMinutes = 60,
    [string] $SupportFolder,
    [ValidateRange(0.50, 0.95)] [double] $MemoryCeiling,
    [ValidateRange(1, 8)] [int] $Workers,
    [string] $PolicyVersion = (Get-Date -Format 'yyyy-MM-dd'),
    [string] $LogFile = (Join-Path $env:TEMP 'DocumentWorkbench-install.log'),
    [switch] $SkipInstall
)

$ErrorActionPreference = 'Stop'

function Test-Admin {
    $principal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
    return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

if (-not (Test-Admin)) {
    Write-Error 'Run this script as Administrator (it installs for all users and protects the policy file).'
    exit 1
}

# ------------------------------------------------------------------ 1. install
if (-not $SkipInstall) {
    $msi = (Resolve-Path $Installer).Path
    Write-Host "Installing $msi (log: $LogFile) ..."
    $process = Start-Process -FilePath 'msiexec.exe' -Wait -PassThru -ArgumentList @(
        '/i', "`"$msi`"", '/qn', '/norestart', '/l*v', "`"$LogFile`"")
    if ($process.ExitCode -ne 0 -and $process.ExitCode -ne 3010) {
        Write-Error "msiexec failed with exit code $($process.ExitCode); see $LogFile"
        exit $process.ExitCode
    }
    Write-Host 'Installed.'
}

# ------------------------------------------------------------------ 2. policy
$policyDir = Join-Path $env:ProgramData 'DocumentWorkbench'
$policyFile = Join-Path $policyDir 'policy.properties'
New-Item -ItemType Directory -Force -Path $policyDir | Out-Null

function Escape([string] $value) {
    # .properties values: backslashes must be doubled (UNC paths, Windows paths)
    return $value.Replace('\', '\\')
}

$generated = @()
if ($DisableAI) { $generated += 'ai.enabled=false' }
if ($DisableWeb) { $generated += 'web.enabled=false' }
if ($DisableLan) { $generated += 'lan.enabled=false' }
if ($RequireLanSecret) { $generated += 'lan.requireSecret=true' }
if ($AdminPassphraseHash) {
    if (-not $AdminPassphraseHash.StartsWith('pbkdf2$')) {
        Write-Error 'AdminPassphraseHash must be the pbkdf2$... value printed by: dwb-cli.exe --hash-passphrase'
        exit 1
    }
    $generated += "admin.passphrase.hash=$AdminPassphraseHash"
}
if ($ReportFolder) {
    $generated += "report.folder=$(Escape $ReportFolder)"
    $generated += "report.intervalMinutes=$ReportIntervalMinutes"
}
if ($SupportFolder) { $generated += "support.folder=$(Escape $SupportFolder)" }
if ($PSBoundParameters.ContainsKey('MemoryCeiling')) {
    $generated += 'memory.ceiling=' + $MemoryCeiling.ToString([Globalization.CultureInfo]::InvariantCulture)
}
if ($PSBoundParameters.ContainsKey('Workers')) { $generated += "workers=$Workers" }

$utf8NoBom = New-Object Text.UTF8Encoding $false
if ($Policy) {
    Copy-Item -Path (Resolve-Path $Policy).Path -Destination $policyFile -Force
    Write-Host "Policy installed from $Policy"
    if ($generated.Count -gt 0) {
        Write-Warning 'Both -Policy and policy switches were given; the switches are appended to the file.'
        [IO.File]::AppendAllText($policyFile, "`r`n" + ($generated -join "`r`n") + "`r`n", $utf8NoBom)
    }
} elseif ($generated.Count -gt 0) {
    $text = @("# Generated by Install-DocumentWorkbench.ps1 on $(Get-Date -Format s)",
              "policy.version=$PolicyVersion") + $generated
    [IO.File]::WriteAllText($policyFile, ($text -join "`r`n") + "`r`n", $utf8NoBom)
    Write-Host "Policy written to $policyFile"
} else {
    Write-Host 'No policy given: settings stay under each user''s control.'
}

# ------------------------------------------------------------------ 3. protect the policy folder
# S-1-5-32-544 Administrators, S-1-5-18 SYSTEM, S-1-5-32-545 Users (language-independent)
& icacls.exe $policyDir /inheritance:r /grant:r '*S-1-5-32-544:(OI)(CI)F' '*S-1-5-18:(OI)(CI)F' `
    '*S-1-5-32-545:(OI)(CI)RX' | Out-Null
if ($LASTEXITCODE -ne 0) {
    Write-Error "icacls failed ($LASTEXITCODE): the policy folder is not protected"
    exit $LASTEXITCODE
}
if (Test-Path $policyFile) {
    & icacls.exe $policyFile /reset | Out-Null
}
Write-Host "Policy folder protected: Users can read $policyDir but not change it."

if ($ReportFolder -and -not (Test-Path $ReportFolder)) {
    Write-Warning "Report folder $ReportFolder is not reachable from this machine now; reports resume when it is."
}
Write-Host 'Done.'
exit 0
